INSTALLDIR = $(DESTDIR)

all:
	@echo "Necessitats concretes."
	@echo "Nothing here."

clean:
	@echo "Netejar fitxers."
	@echo "Nothing here."

install:
	@echo "Make directory"
	mkdir -p $(INSTALLDIR)/usr/sbin
	@echo "Install files"	
	install -m 0755 stvclient $(INSTALLDIR)/usr/sbin
